#!/usr/bin/env ruby

# Modified from http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen
git_bundles = [
  "git://git.wincent.com/command-t.git",
  "git://github.com/altercation/vim-colors-solarized.git"
  "git://github.com/edsono/vim-matchit.git",
  "git://github.com/majutsushi/tagbar.git",
  "git://github.com/msanders/snipmate.vim.git",
  # "git://github.com/scrooloose/nerdcommenter.git",
  "git://github.com/scrooloose/nerdtree.git",
  # "git://github.com/timcharper/textile.vim.git",
  "git://github.com/Townk/vim-autoclose.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  # "git://github.com/tpope/vim-haml.git",
  # "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  # "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/vim-scripts/python_match.vim.git",
  "git://github.com/fholgado/minibufexpl.vim.git",
  "git://github.com/ervandew/supertab.git",
  # "git://github.com/yumyai/taglist.vim",
  "git://github.com/kevinw/pyflakes-vim",
]

vim_org_scripts = [
#  ["gist",          "12732", "plugin"],
#  ["minibufexpl",   "159",   ""],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

# TODO: automate "/usr/bin/rake make" in command-t directory

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

